#!/usr/bin/env python3
"""
Safely inject FAQ sections and internal links into data.ts article content.
Uses unique content markers to find insertion points.
"""
import json
import re

# Load the generated content
with open('/Users/holmes/.openclaw/workspace/projects/everlasting-goods/site-v2/.tmp_seo_enhance.py') as f:
    pass  # Not needed

# The generated FAQ/link content (from previous run)
generated = json.loads(r'''
{
  "best-cast-iron-skillets-that-last-forever": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-kitchen-knives-that-last-a-lifetime\">Best Kitchen Knives That Last a Lifetime</a></li>\n<li><a href=\"/articles/best-dutch-ovens-that-last-forever\">Best Dutch Ovens That Last Forever</a></li>\n<li><a href=\"/articles/best-buy-it-for-life-backpacks\">Best Buy It For Life Backpacks</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What are the best cast iron skillets that last forever?</h3><p>Le Creuset, Lodge, and Matfer Bourgeat offer durable cast iron skillets known for longevity.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How do I choose a high-quality cast iron skillet?</h3><p>Look for heavy gauge material, good craftsmanship, and a well-established brand reputation.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Why are Le Creuset cast iron skillets considered the best?</h3><p>Le Creuset skillets are renowned for their even heat distribution, superior quality, and lasting durability.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What makes Lodge cast iron skillets stand out as durable kitchen tools?</h3><p>Lodge skillets are affordable, well-made, and pre-seasoned to provide excellent cooking performance over many years.</p></div>\n</div>",
  "best-buy-it-for-life-backpacks": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-cast-iron-skillets-that-last-forever\">Best Cast Iron Skillets That Last Forever</a></li>\n<li><a href=\"/articles/best-kitchen-knives-that-last-a-lifetime\">Best Kitchen Knives That Last a Lifetime</a></li>\n<li><a href=\"/articles/best-leather-boots-that-last-20-years\">Best Leather Boots That Last 20+ Years</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What makes a BIFL backpack durable?</h3><p>BIFL backpacks use high-quality materials like 1000D Cordura nylon, YKK zippers, and reinforced stitching to ensure long-lasting durability.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How do these backpacks handle heavy loads for outdoor activities?</h3><p>They are designed with multiple compartments, padded straps, and reinforced frames to distribute weight evenly and provide comfort during extended use.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Are BIFL backpacks waterproof?</h3><p>While not fully waterproof, they often include water-resistant materials and coatings to protect your gear from light rain or splashes.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What warranty should I expect from a BIFL backpack?</h3><p>The best BIFL backpacks come with lifetime warranties that cover manufacturing defects and often include free repairs.</p></div>\n</div>",
  "best-kitchen-knives-that-last-a-lifetime": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-cast-iron-skillets-that-last-forever\">Best Cast Iron Skillets That Last Forever</a></li>\n<li><a href=\"/articles/best-dutch-ovens-that-last-forever\">Best Dutch Ovens That Last Forever</a></li>\n<li><a href=\"/articles/best-buy-it-for-life-backpacks\">Best Buy It For Life Backpacks</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What are the best materials for kitchen knives that last a lifetime?</h3><p>High-carbon stainless steel is ideal as it balances durability with rust resistance and edge retention.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Which knife brands are known for their longevity and quality?</h3><p>Wusthof, Victorinox, Shun, and Global offer premium knives made from high-quality materials with expert craftsmanship.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How do I maintain my kitchen knives to ensure they last a lifetime?</h3><p>Regular honing with a steel rod, professional sharpening once or twice a year, hand washing, and proper storage will extend your knives' life significantly.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What types of knives should be in a buy-it-for-life kitchen set?</h3><p>A chef's knife, paring knife, utility knife, and bread knife are essential for comprehensive kitchen tasks.</p></div>\n</div>",
  "best-leather-boots-that-last-20-years": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-red-wing-boots-a-complete-buyer-s-guide\">Best Red Wing Boots: A Complete Buyer's Guide</a></li>\n<li><a href=\"/articles/best-cast-iron-skillets-that-last-forever\">Best Cast Iron Skillets That Last Forever</a></li>\n<li><a href=\"/articles/best-buy-it-for-life-backpacks\">Best Buy It For Life Backpacks</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What features should I look for in leather boots that last 20+ years?</h3><p>Look for full-grain leather, Goodyear welt construction, reinforced stitching, and a sturdy Vibram sole with good traction.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How do I take care of leather boots to ensure they last decades?</h3><p>Clean with a horsehair brush after wearing, condition the leather every 2-3 months, waterproof annually, and store in a cool dry place away from direct sunlight.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Which boot brands produce leather boots that last 20+ years?</h3><p>Red Wing, Wolverine, and Blundstone are known for high-quality craftsmanship and materials that ensure exceptional longevity.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What type of soles provide the longest-lasting support?</h3><p>Vibram rubber soles are excellent choices as they offer superior traction and wear resistance over many years of heavy use.</p></div>\n</div>",
  "best-edc-flashlights-that-last-forever": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-mechanical-watches-that-last-a-lifetime\">Best Mechanical Watches That Last a Lifetime</a></li>\n<li><a href=\"/articles/best-stainless-steel-water-bottles-that-last-forever\">Best Stainless Steel Water Bottles That Last Forever</a></li>\n<li><a href=\"/articles/best-buy-it-for-life-backpacks\">Best Buy It For Life Backpacks</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What are the best EDC flashlights that last forever?</h3><p>SureFire EDC1-DFT, Fenix E18R, and Streamlight ProTac are top choices for their superior build quality and lifetime warranties.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How do I ensure my EDC flashlight lasts a lifetime?</h3><p>Keep it clean and dry, use recommended batteries, avoid dropping, and periodically charge rechargeable models to maintain battery health.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What features should I look for in a durable EDC flashlight?</h3><p>Look for aerospace-grade aluminum construction, IPX8 water resistance, quality switches, and dual-fuel battery compatibility.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Can LED flashlights really last forever?</h3><p>While LEDs can have lifespans of tens of thousands of hours, regular maintenance and proper usage are key to maximizing the overall flashlight lifespan.</p></div>\n</div>",
  "best-dutch-ovens-that-last-forever": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-cast-iron-skillets-that-last-forever\">Best Cast Iron Skillets That Last Forever</a></li>\n<li><a href=\"/articles/best-kitchen-knives-that-last-a-lifetime\">Best Kitchen Knives That Last a Lifetime</a></li>\n<li><a href=\"/articles/best-buy-it-for-life-backpacks\">Best Buy It For Life Backpacks</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What are the top Dutch ovens built to last forever?</h3><p>Le Creuset, Staub, and Lodge enameled cast iron Dutch ovens are renowned for their durability and longevity.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Why are Lodge Dutch ovens considered durable?</h3><p>Lodge Dutch ovens are made from pre-seasoned cast iron, which retains heat exceptionally well and develops a natural non-stick surface over time.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How does Le Creuset's Dutch oven stand out in terms of durability?</h3><p>Le Creuset Dutch ovens feature triple-layer enamel that resists chipping and staining, ensuring the pot remains functional for decades.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What materials make Dutch ovens last the longest?</h3><p>Enameled cast iron is the most durable choice, combining the heat retention of cast iron with the easy maintenance of a vitreous enamel coating.</p></div>\n</div>",
  "best-mechanical-watches-that-last-a-lifetime": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-edc-flashlights-that-last-forever\">Best EDC Flashlights That Last Forever</a></li>\n<li><a href=\"/articles/best-stainless-steel-water-bottles-that-last-forever\">Best Stainless Steel Water Bottles That Last Forever</a></li>\n<li><a href=\"/articles/best-leather-boots-that-last-20-years\">Best Leather Boots That Last 20+ Years</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What are the top mechanical watch brands known for lasting a lifetime?</h3><p>Rolex, Omega, and Seiko are renowned for crafting durable, long-lasting mechanical watches with excellent serviceability.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Why are mechanical watches considered a buy-it-for-life investment?</h3><p>Mechanical watches have no electronic components to fail, are fully serviceable by watchmakers worldwide, and often appreciate in value over time.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What features should I look for in a lifetime mechanical watch?</h3><p>Look for water resistance, robust case materials like 316L stainless steel, an in-house movement, and a proven service history from the manufacturer.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How do I ensure my mechanical watch lasts a lifetime?</h3><p>Service it every 5-10 years with an authorized watchmaker, avoid strong magnetic fields, and test water resistance annually if you swim with it.</p></div>\n</div>",
  "best-woodworking-hand-tools-that-last-forever": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-cast-iron-skillets-that-last-forever\">Best Cast Iron Skillets That Last Forever</a></li>\n<li><a href=\"/articles/best-buy-it-for-life-backpacks\">Best Buy It For Life Backpacks</a></li>\n<li><a href=\"/articles/best-kitchen-knives-that-last-a-lifetime\">Best Kitchen Knives That Last a Lifetime</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What woodworking hand tools are known to last forever?</h3><p>Lie-Nielsen hand planes, Two Cherries chisels, and Veritas marking gauges are known for exceptional longevity due to their premium materials and construction.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Why do certain woodworking hand tools last a lifetime?</h3><p>Tools made from high-carbon steel with cast iron or forged steel bodies have no motors or electronics to fail and can be sharpened indefinitely.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How can I maintain woodworking hand tools for long-term use?</h3><p>Sharpen regularly with waterstones, wipe metal surfaces with camellia oil after use, and store in a dry environment where blades cannot contact each other.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What are the best brands for durable woodworking hand tools?</h3><p>Lie-Nielsen, Veritas, Lee Valley, Narex, and Two Cherries are renowned for producing high-quality, long-lasting woodworking hand tools.</p></div>\n</div>",
  "best-lodge-cast-iron-pieces-the-complete-collection-guide": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-cast-iron-skillets-that-last-forever\">Best Cast Iron Skillets That Last Forever</a></li>\n<li><a href=\"/articles/best-dutch-ovens-that-last-forever\">Best Dutch Ovens That Last Forever</a></li>\n<li><a href=\"/articles/best-buy-it-for-life-backpacks\">Best Buy It For Life Backpacks</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What are the key features to look for in Lodge cast iron pieces?</h3><p>Look for pre-seasoned cooking surfaces, even heat distribution, compatibility with all stovetop types including induction, and a solid warranty.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Why choose Lodge cast iron over other brands?</h3><p>Lodge offers exceptional durability at an affordable price point, and their products are pre-seasoned and ready to use right out of the box.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How do I maintain Lodge cast iron to ensure longevity?</h3><p>Clean with hot water and a stiff brush, dry thoroughly, and apply a thin coat of cooking oil after each wash to maintain the seasoning.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What Lodge pieces are essential for every kitchen?</h3><p>A 12-inch skillet, a Dutch oven, and a griddle cover the vast majority of cooking needs and make an excellent starter collection.</p></div>\n</div>",
  "best-stainless-steel-water-bottles-that-last-forever": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-edc-flashlights-that-last-forever\">Best EDC Flashlights That Last Forever</a></li>\n<li><a href=\"/articles/best-mechanical-watches-that-last-a-lifetime\">Best Mechanical Watches That Last a Lifetime</a></li>\n<li><a href=\"/articles/best-buy-it-for-life-backpacks\">Best Buy It For Life Backpacks</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What are the top stainless steel water bottles for durability?</h3><p>Hydro Flask, YETI Rambler, and Klean Kanteen are highly regarded for their durable construction and long-lasting use.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Why are stainless steel water bottles considered buy-it-for-life items?</h3><p>They are made from corrosion-resistant 18/8 stainless steel that maintains structural integrity over years of daily use without degrading.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How can I ensure my stainless steel water bottle lasts a lifetime?</h3><p>Clean regularly with mild soap, avoid dropping on hard surfaces, and replace silicone seals periodically to maintain leak-proof performance.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What features make a stainless steel water bottle truly durable?</h3><p>Double-wall vacuum insulation, thick 18/8 stainless steel construction, powder-coated exterior, and quality lids with replaceable gaskets.</p></div>\n</div>",
  "best-buy-it-for-life-gifts-under-50-quality-picks-that-last": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-cast-iron-skillets-that-last-forever\">Best Cast Iron Skillets That Last Forever</a></li>\n<li><a href=\"/articles/best-kitchen-knives-that-last-a-lifetime\">Best Kitchen Knives That Last a Lifetime</a></li>\n<li><a href=\"/articles/best-edc-flashlights-that-last-forever\">Best EDC Flashlights That Last Forever</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What are the best buy-it-for-life gifts under $50?</h3><p>A Victorinox Swiss Army Knife, Darn Tough socks, Opinel pocket knife, and Lodge cast iron skillet are all excellent BIFL gifts under $50.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Why choose durable goods as gifts?</h3><p>Durable items provide lasting value, reduce waste, and show thoughtfulness by giving something the recipient will use and appreciate for years.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Where can I find reliable BIFL items under $50?</h3><p>Brands like Victorinox, Lodge, Darn Tough, and Opinel offer excellent durable products well within the $50 budget.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What makes a good buy-it-for-life gift?</h3><p>A good BIFL gift is made from premium materials, backed by a strong warranty, and designed to perform well over many years of regular use.</p></div>\n</div>",
  "best-red-wing-boots-a-complete-buyer-s-guide": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-leather-boots-that-last-20-years\">Best Leather Boots That Last 20+ Years</a></li>\n<li><a href=\"/articles/best-cast-iron-skillets-that-last-forever\">Best Cast Iron Skillets That Last Forever</a></li>\n<li><a href=\"/articles/best-buy-it-for-life-backpacks\">Best Buy It For Life Backpacks</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What are the most popular Red Wing boot models?</h3><p>The Iron Ranger, Classic Moc, and Blacksmith are among the most popular models for their durability, comfort, and timeless style.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How do I ensure my Red Wing boots fit properly?</h3><p>Visit an authorized retailer to try on different sizes, as Red Wing sizing can vary by model and last shape.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What is the average lifespan of Red Wing boots?</h3><p>With proper care including regular conditioning and resoling, Red Wing boots can last 20+ years of regular wear.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How should I maintain Red Wing boots for maximum longevity?</h3><p>Clean with a horsehair brush after wearing, condition the leather every 2-3 months, and have them resoled when the soles wear down.</p></div>\n</div>",
  "best-buy-it-for-life-chef-s-knives-professional-picks": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-kitchen-knives-that-last-a-lifetime\">Best Kitchen Knives That Last a Lifetime</a></li>\n<li><a href=\"/articles/best-cast-iron-skillets-that-last-forever\">Best Cast Iron Skillets That Last Forever</a></li>\n<li><a href=\"/articles/best-dutch-ovens-that-last-forever\">Best Dutch Ovens That Last Forever</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What are the key features to look for in a BIFL chef's knife?</h3><p>Look for high-carbon stainless steel blades, full-tang construction, comfortable ergonomic handles, and a manufacturer's lifetime warranty.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Why invest in a professional-grade chef's knife?</h3><p>Professional-grade knives maintain their edge longer, offer better balance and control, and are designed to be sharpened and used for decades.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How do I keep a BIFL chef's knife in top condition?</h3><p>Hone before each use, sharpen professionally once or twice a year, hand wash immediately after use, and store in a knife block or magnetic strip.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Which chef's knife brands offer the best lifetime value?</h3><p>Wusthof, Victorinox, MAC, and Shun all offer exceptional quality knives backed by strong warranties and proven long-term performance.</p></div>\n</div>",
  "best-buy-it-for-life-bifl-everyday-carry-pens-pens-that-last-a-lifetime": "\n<h2 id=\"related-reading\">Related Reading</h2>\n<p>If you enjoyed this guide, check out these related articles:</p>\n<ul>\n<li><a href=\"/articles/best-edc-flashlights-that-last-forever\">Best EDC Flashlights That Last Forever</a></li>\n<li><a href=\"/articles/best-mechanical-watches-that-last-a-lifetime\">Best Mechanical Watches That Last a Lifetime</a></li>\n<li><a href=\"/articles/best-stainless-steel-water-bottles-that-last-forever\">Best Stainless Steel Water Bottles That Last Forever</a></li>\n</ul>\n\n<h2 id=\"faq\">Frequently Asked Questions</h2>\n<div class=\"faq-section\">\n<div class=\"faq-item\"><h3 class=\"faq-question\">What are the best BIFL everyday carry pens?</h3><p>The Fisher Space Pen, Parker Jotter Stainless Steel, rOtring 600, and Tactile Turn Bolt Action are all excellent BIFL EDC pen choices.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">Why invest in a buy-it-for-life pen?</h3><p>BIFL pens offer superior build quality and longevity, with refillable ink systems that make them more cost-effective and reliable over time.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">How do BIFL pens compare to disposable pens?</h3><p>BIFL pens use superior materials and precision mechanisms that provide smoother writing, better durability, and a more satisfying experience.</p></div>\n<div class=\"faq-item\"><h3 class=\"faq-question\">What features make a pen truly buy-it-for-life?</h3><p>Look for durable materials like stainless steel or brass, robust click or twist mechanisms, widely available refills, and a comfortable grip design.</p></div>\n</div>"
}
''')

# Read data.ts
with open('/Users/holmes/.openclaw/workspace/projects/everlasting-goods/site-v2/src/lib/data.ts', 'r') as f:
    content = f.read()

# For each article, find the end of its content and inject the HTML
# Strategy: find the content closing pattern for each slug
# Each article's content ends with `\n    `,  or ``,  (for empty ones)

# Map slug to a unique string near the end of its content that we can use as an anchor
# We'll find the pattern: slug definition, then the content closing backtick
for slug, html in generated.items():
    # Escape special regex chars in the HTML we're injecting
    # We need to find the closing of the content for this article
    # The content field ends with either:
    # 1. `\n    `,   (for articles with template literal content)
    # 2. ``,        (for empty content)

    # Find the slug in the file
    slug_escaped = re.escape(slug)

    # Find the content field for this slug's article
    # Pattern: slug: "SLUG", ... content: `...`
    # We need to find the closing backtick of the content for this specific article

    # Strategy: find `slug: "SLUG"` then find the next `content: \`` then find the matching closing backtick
    slug_pos = content.find(f'slug: "{slug}"')
    if slug_pos == -1:
        print(f"WARNING: Could not find slug {slug}")
        continue

    # Find `content:` after this slug
    content_start = content.find('content:', slug_pos)
    if content_start == -1:
        print(f"WARNING: Could not find content for {slug}")
        continue

    # Find the opening backtick
    backtick_start = content.find('`', content_start)
    if backtick_start == -1:
        print(f"WARNING: Could not find backtick for {slug}")
        continue

    # Now find the matching closing backtick
    # We need to handle nested backticks carefully, but template literals
    # in this file don't have nested ones, so find the next backtick
    # But we need to skip escaped backticks... actually these are template literals
    # and the content is HTML so there shouldn't be backticks in the content

    # Find closing backtick - it's the next ` that's followed by , or }
    pos = backtick_start + 1
    while pos < len(content):
        if content[pos] == '`':
            # Check if this is the closing backtick
            # Look ahead for comma or closing brace
            rest = content[pos+1:pos+20].strip()
            if rest.startswith(',') or rest.startswith('}'):
                break
        pos += 1

    if pos >= len(content):
        print(f"WARNING: Could not find closing backtick for {slug}")
        continue

    closing_backtick_pos = pos

    # Check if content is empty
    current_content = content[backtick_start+1:closing_backtick_pos]
    if not current_content.strip():
        print(f"Skipping {slug} (empty content)")
        continue

    # Check if FAQ already exists
    if 'faq-section' in current_content:
        print(f"Skipping {slug} (FAQ already exists)")
        continue

    # Inject the HTML before the closing backtick
    # Need to escape backticks and ${} in the HTML for template literals
    safe_html = html.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
    # Actually, the HTML doesn't contain backticks or ${}, so we're fine
    # But let's be safe
    safe_html = html

    content = content[:closing_backtick_pos] + '\n' + safe_html + '\n    ' + content[closing_backtick_pos:]
    print(f"Injected content for {slug}")

# Write the modified file
with open('/Users/holmes/.openclaw/workspace/projects/everlasting-goods/site-v2/src/lib/data.ts', 'w') as f:
    f.write(content)

print("Done! data.ts updated successfully.")
