import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Evidence & Database Methodology", description: "Evidence tiers, field-level citations, freshness rules, authorship, and correction policy for the Everlasting Goods database.", alternates: { canonical: "https://everlasting-goods.com/methodology" } };

const tiers = [
  ["T1 — First-party", "A dated note or media record supplied by Daniel or the shop. Hermes cannot create or extend T1 evidence."],
  ["T2 — Manufacturer documentation", "An official product page, manual, warranty document, parts catalog, or manufacturer support page with retrieval date."],
  ["T3 — Corroborated owner reports", "At least three independent cited sources support the same claim. Each source remains attached to the field."],
  ["T4 — Not yet verified", "The field is not published as fact. The visible value remains “Not yet verified.”"],
] as const;

export default function MethodologyPage() {
  return <main className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8"><p className="text-sm font-semibold uppercase tracking-wider text-brown-accent">Methodology</p><h1 className="mt-4 font-serif text-5xl font-bold text-charcoal">Evidence lives with the field.</h1><p className="mt-6 text-xl leading-relaxed text-charcoal/65">The tracked SQLite database is the factual source. Pages, comparisons, freshness queues, and structured data are generated from it. A claim that exists only in prose is a defect.</p><section className="mt-12"><h2 className="font-serif text-3xl font-bold text-charcoal">Evidence tiers</h2><div className="mt-6 space-y-4">{tiers.map(([name, description]) => <div key={name} className="rounded-2xl border border-cream-200 bg-white p-6"><h3 className="font-serif text-xl font-bold text-charcoal">{name}</h3><p className="mt-2 text-charcoal/65">{description}</p></div>)}</div></section><section className="mt-12 grid gap-6 md:grid-cols-2"><div className="rounded-2xl bg-cream-100 p-7"><h2 className="font-serif text-2xl font-bold text-charcoal">Freshness</h2><p className="mt-3 text-charcoal/65">Price fields re-enter verification after 30 days. Warranty and parts fields re-enter after 180 days. Pages display the verification and stale-after dates.</p></div><div className="rounded-2xl bg-cream-100 p-7"><h2 className="font-serif text-2xl font-bold text-charcoal">Economics</h2><p className="mt-3 text-charcoal/65">Cost per year is calculated only when both price and expected service life are verified: (price ÷ service life) + annual maintenance.</p></div><div className="rounded-2xl bg-cream-100 p-7"><h2 className="font-serif text-2xl font-bold text-charcoal">Authorship</h2><p className="mt-3 text-charcoal/65">The public author is Everlasting Goods Editorial Team. Testing, ownership, and repair history appear only as attributed T1 evidence.</p></div><div className="rounded-2xl bg-cream-100 p-7"><h2 className="font-serif text-2xl font-bold text-charcoal">Commercial links</h2><p className="mt-3 text-charcoal/65">Only exact-model affiliate destinations are eligible. Search-result destinations, stale ratings, and undated prices are not published.</p></div></section><section className="mt-12 rounded-2xl border border-forest-500/15 bg-forest-500/5 p-8"><h2 className="font-serif text-2xl font-bold text-charcoal">Corrections</h2><p className="mt-3 text-charcoal/65">Send the exact URL, field, and source through the <Link href="/contact" className="font-semibold text-forest-600 underline">contact page</Link>. Material changes are recorded in git and update the field verification date only after the source is retrieved.</p></section></main>;
}
