from pathlib import Path
import re

path = Path('/Users/holmes/.openclaw/workspace/projects/everlasting-goods/site-v2/src/lib/data.ts')
text = path.read_text()

replacements = {
    "If you are wondering what to buy in Japan, this is the short answer: skip novelty, buy tools.</p>": "If you are wondering what to buy in Japan, this is the short answer: skip novelty, buy tools. That same bias toward boring, durable utility is why a <a href='/articles/best-stainless-steel-water-bottles-that-last-forever'>stainless steel bottle that lasts forever</a> or a <a href='/articles/best-mechanical-watches-that-last-a-lifetime'>mechanical watch that lasts a lifetime</a> still makes more sense than trendy gear that ages out fast.</p>",
    "<p>The sweet spot is not tourist trinkets. It is practical stuff: thermoses that actually hold heat, shears that keep cutting, pens that make you want to write by hand, and cookware that will still be working when cheaper alternatives are in a landfill.</p>": "<p>The sweet spot is not tourist trinkets. It is practical stuff: thermoses that actually hold heat, shears that keep cutting, pens that make you want to write by hand, and cookware that will still be working when cheaper alternatives are in a landfill. If your kitchen priorities lean harder toward prep gear, our guides to <a href='/articles/best-kitchen-knives-that-last-a-lifetime'>kitchen knives that last a lifetime</a> and <a href='/articles/best-peelers-that-last-for-years'>peelers that last for years</a> play the same game.</p>",
    "<p>But compared with tablets and phones, e-readers are freakishly durable. E Ink displays sip power, the hardware is simple, and most people are not hammering the processor all day. Buy the right one and you can easily get five to ten years out of it, sometimes more.</p>": "<p>But compared with tablets and phones, e-readers are freakishly durable. E Ink displays sip power, the hardware is simple, and most people are not hammering the processor all day. Buy the right one and you can easily get five to ten years out of it, sometimes more. That makes them closer in spirit to a <a href='/articles/best-stainless-steel-water-bottles-that-last-forever'>stainless steel bottle that lasts forever</a> than to a disposable gadget churn machine.</p>",
    "<p>Also, avoid overpaying for storage unless you read comics or keep massive local libraries. Text files are tiny. People routinely spend extra on capacity they will never touch.</p>": "<p>Also, avoid overpaying for storage unless you read comics or keep massive local libraries. Text files are tiny. People routinely spend extra on capacity they will never touch. The same restraint applies when shopping for <a href='/articles/best-buy-it-for-life-gifts-under-50-quality-picks-that-last'>BIFL gifts under $50</a> or <a href='/articles/best-buy-it-for-life-japan-picks'>durable buys from Japan</a>: fewer gimmicks, better fundamentals.</p>",
    "<p>The current spike in interest around durable peelers makes sense because people are finally getting tired of replacing flimsy kitchen tools that should not fail in the first place.</p>": "<p>The current spike in interest around durable peelers makes sense because people are finally getting tired of replacing flimsy kitchen tools that should not fail in the first place. Anyone who has already upgraded to a <a href='/articles/best-kitchen-knives-that-last-a-lifetime'>real chef's knife</a> or a <a href='/articles/best-cast-iron-skillets-that-last-forever'>cast iron skillet that lasts forever</a> will recognize the pattern.</p>",
    "<p><strong>Choose stainless steel</strong> if you want the safest all-around option. It is less exotic, more tolerant of abuse, and easier to trust in a busy kitchen.</p>": "<p><strong>Choose stainless steel</strong> if you want the safest all-around option. It is less exotic, more tolerant of abuse, and easier to trust in a busy kitchen. Stainless also pairs well with the same practical mindset behind <a href='/articles/best-dutch-ovens-that-last-forever'>Dutch ovens that last forever</a> and <a href='/articles/best-buy-it-for-life-chef-s-knives-professional-picks'>professional chef's knives built for the long haul</a>.</p>",
    "<li><strong>LEGO Classic Creative Brick Box</strong>: A staple in any child’s toy collection, LEGO bricks offer unparalleled creativity and construction potential. The set contains a variety of pieces that can be assembled into an endless array of designs, keeping kids engaged for hours.<br><a href=\"https://www.amazon.com/s?k=LEGO+classic+creative+brick+box&tag=everlastin09f-20\" target=\"_blank\" rel=\"nofollow noopener\">Shop Now</a></li>": "<li><strong>LEGO Classic Creative Brick Box</strong>: A staple in any child’s toy collection, LEGO bricks offer unparalleled creativity and construction potential. The set contains a variety of pieces that can be assembled into an endless array of designs, keeping kids engaged for hours. For gift ideas outside the playroom, our guide to <a href='/articles/best-buy-it-for-life-gifts-under-50-quality-picks-that-last'>buy-it-for-life gifts under $50</a> is a useful companion.<br><a href=\"https://www.amazon.com/s?k=LEGO+classic+creative+brick+box&tag=everlastin09f-20\" target=\"_blank\" rel=\"nofollow noopener\">Shop Now</a></li>",
    "<li><strong>Warranty & Customer Reviews</strong>: A good warranty can give you peace of mind. Also, read customer reviews to understand the product’s durability from real users.</li>": "<li><strong>Warranty & Customer Reviews</strong>: A good warranty can give you peace of mind. Also, read customer reviews to understand the product’s durability from real users, just like you would for <a href='/articles/best-buy-it-for-life-backpacks'>buy-it-for-life backpacks</a> or <a href='/articles/best-buy-it-for-life-rain-jackets'>rain jackets that actually hold up</a>.</li>",
    "<p>A recent post on <a href=\"https://www.buyitforlife.com/trending/best-estwing-hammers-longevity/\" target=\"_blank\" rel=\"nofollow noopener\">BuyItForLife</a> has highlighted the enduring reputation and quality of Estwing hammers. With a strong engagement score, it's clear that professionals and DIY enthusiasts alike are recognizing the value in owning tools that stand the test of time.</p>": "<p>A recent post on <a href=\"https://www.buyitforlife.com/trending/best-estwing-hammers-longevity/\" target=\"_blank\" rel=\"nofollow noopener\">BuyItForLife</a> has highlighted the enduring reputation and quality of Estwing hammers. With a strong engagement score, it's clear that professionals and DIY enthusiasts alike are recognizing the value in owning tools that stand the test of time. If you lean more toward shop precision than demolition force, our guide to <a href='/articles/best-woodworking-hand-tools-that-last-forever'>woodworking hand tools that last forever</a> belongs on your list too.</p>",
    "<li><strong>Ergonomics:</strong> Choose a hammer that fits comfortably in your hand and allows for smooth, controlled strikes.</li>": "<li><strong>Ergonomics:</strong> Choose a hammer that fits comfortably in your hand and allows for smooth, controlled strikes. The same principle matters when choosing <a href='/articles/best-woodworking-hand-tools-that-last-forever'>long-lasting hand tools</a> or even <a href='/articles/best-edc-flashlights-that-last-forever'>an EDC flashlight you actually carry</a>.</li>",
    "<p>The debate between Moen vs Kohler in terms of faucet durability is heating up on BuyItForLife, with users weighing the pros and cons of each brand's kitchen faucets. When you're considering a fixture that will serve your home for years to come, it pays to be discerning about materials and construction. A solid brass faucet from <a href=\"https://www.amazon.com/s?k=solid+brass+faucet&tag=everlastin09f-20\" target=\"_blank\" rel=\"nofollow noopener\">Moentm</a> or <a href=\"https://www.amazon.com/s?k=solid+brass+faucet&tag=everlastin09f-20\" target=\"_blank\" rel=\"nofollow noopener\">Delta</a>, for instance, can offer superior longevity and performance compared to less durable alternatives.</p>": "<p>The debate between Moen vs Kohler in terms of faucet durability is heating up on BuyItForLife, with users weighing the pros and cons of each brand's kitchen faucets. When you're considering a fixture that will serve your home for years to come, it pays to be discerning about materials and construction. A solid brass faucet from <a href=\"https://www.amazon.com/s?k=solid+brass+faucet&tag=everlastin09f-20\" target=\"_blank\" rel=\"nofollow noopener\">Moentm</a> or <a href=\"https://www.amazon.com/s?k=solid+brass+faucet&tag=everlastin09f-20\" target=\"_blank\" rel=\"nofollow noopener\">Delta</a>, for instance, can offer superior longevity and performance compared to less durable alternatives. It is the same logic that makes <a href='/articles/best-stainless-steel-water-bottles-that-last-forever'>stainless steel water bottles</a> and <a href='/articles/best-dutch-ovens-that-last-forever'>enameled Dutch ovens</a> safer long-term bets than plated junk.</p>",
    "<li><strong>Mechanical Design:</strong> Look for features such as a ceramic disc valve, which provides longevity and durability.</li>": "<li><strong>Mechanical Design:</strong> Look for features such as a ceramic disc valve, which provides longevity and durability. If replaceable parts and serviceability matter to you, that same mindset shows up in <a href='/articles/best-mechanical-watches-that-last-a-lifetime'>mechanical watches built for service</a> and <a href='/articles/best-red-wing-boots-a-complete-buyer-s-guide'>resoleable Red Wing boots</a>.</li>",
    "<p>There's a reason your grandmother's cast iron skillet is still going strong after 60 years. Cast iron is, quite simply, the most durable cookware material on earth. When properly cared for, a cast iron skillet will last not just your lifetime, but your children's and grandchildren's too.</p>": "<p>There's a reason your grandmother's cast iron skillet is still going strong after 60 years. Cast iron is, quite simply, the most durable cookware material on earth. When properly cared for, a cast iron skillet will last not just your lifetime, but your children's and grandchildren's too. The same heavy-duty logic applies to a <a href='/articles/best-dutch-ovens-that-last-forever'>Dutch oven that lasts forever</a> and even the broader <a href='/articles/best-lodge-cast-iron-pieces-the-complete-collection-guide'>Lodge cast iron collection</a>.</p>",
    "<p>After cooking, rinse with hot water and use a chain mail scrubber or stiff brush to remove food. Dry immediately and completely — water is cast iron's only real enemy. Apply a thin coat of oil while the pan is still warm.</p>": "<p>After cooking, rinse with hot water and use a chain mail scrubber or stiff brush to remove food. Dry immediately and completely — water is cast iron's only real enemy. Apply a thin coat of oil while the pan is still warm. If you are building a durable kitchen kit piece by piece, pair that routine with a <a href='/articles/best-kitchen-knives-that-last-a-lifetime'>chef's knife that lasts a lifetime</a> and a <a href='/articles/best-peelers-that-last-for-years'>peeler that stays useful for years</a>.</p>",
    "<p>The difference between a $50 backpack and a $300+ BIFL pack is enormous. Cheap packs use 300-600D polyester, lightweight zippers, and bar-tack stitching at stress points. BIFL packs use 1000D Cordura or waxed canvas, YKK zippers, and are reinforced far beyond what you'd expect.</p>": "<p>The difference between a $50 backpack and a $300+ BIFL pack is enormous. Cheap packs use 300-600D polyester, lightweight zippers, and bar-tack stitching at stress points. BIFL packs use 1000D Cordura or waxed canvas, YKK zippers, and are reinforced far beyond what you'd expect. If you are building an everyday setup instead of just a bag, our guides to <a href='/articles/best-bifl-wallets-for-men-leather-wallets-that-age-beautifully'>BIFL wallets</a> and <a href='/articles/best-edc-flashlights-that-last-forever'>EDC flashlights that last forever</a> pair naturally here.</p>",
    "<p>For those who prefer waxed canvas over Cordura, the <a href=\"https://www.amazon.com/dp/B07CJWBN6C?tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">Filson Journeyman</a> is an exceptional choice. Made in Seattle from <a href=\"https://www.amazon.com/s?k=tin+cloth&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">tin cloth</a> and <a href=\"https://www.amazon.com/s?k=bridle+leather&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">bridle leather</a>, it has a heritage look that ages beautifully. <a href=\"https://www.amazon.com/s?k=Filson&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">Filson's</a> been making rugged gear since the Klondike Gold Rush, and their warranty is ironclad.</p>": "<p>For those who prefer waxed canvas over Cordura, the <a href=\"https://www.amazon.com/dp/B07CJWBN6C?tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">Filson Journeyman</a> is an exceptional choice. Made in Seattle from <a href=\"https://www.amazon.com/s?k=tin+cloth&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">tin cloth</a> and <a href=\"https://www.amazon.com/s?k=bridle+leather&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">bridle leather</a>, it has a heritage look that ages beautifully. <a href=\"https://www.amazon.com/s?k=Filson&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">Filson's</a> been making rugged gear since the Klondike Gold Rush, and their warranty is ironclad. Fans of this style should also look at <a href='/articles/best-buy-it-for-life-rain-jackets'>buy-it-for-life rain jackets</a> and <a href='/articles/best-bifl-wallets-for-men-leather-wallets-that-age-beautifully'>leather wallets that age beautifully</a>.</p>",
    "<p>The key is buying a knife that's well-made, comfortable in your hand, and easy to maintain. A BIFL knife doesn't have to cost $300 — in fact, our top pick is under $40.</p>": "<p>The key is buying a knife that's well-made, comfortable in your hand, and easy to maintain. A BIFL knife doesn't have to cost $300 — in fact, our top pick is under $40. If you are outfitting the rest of the kitchen at the same time, a <a href='/articles/best-cast-iron-skillets-that-last-forever'>cast iron skillet</a>, a <a href='/articles/best-dutch-ovens-that-last-forever'>Dutch oven</a>, and even a <a href='/articles/best-peelers-that-last-for-years'>good peeler</a> make the biggest difference fastest.</p>",
    "<p>The most important thing you can do for your knives is keep them sharp. A dull knife is more dangerous than a sharp one because it requires more force, making slips more likely. Invest in a quality whetstone or take your knives to a professional sharpener once or twice a year.</p>": "<p>The most important thing you can do for your knives is keep them sharp. A dull knife is more dangerous than a sharp one because it requires more force, making slips more likely. Invest in a quality whetstone or take your knives to a professional sharpener once or twice a year. That maintenance-first mentality is exactly what separates disposable tools from <a href='/articles/best-buy-it-for-life-chef-s-knives-professional-picks'>professional chef's knives</a> and other genuinely durable kitchen gear.</p>",
    "<p>But it's not just about money. Quality leather boots break in to the exact shape of your feet. After the first few weeks (yes, the break-in is real), they become the most comfortable shoes you own. They develop a patina that tells your story. They're <em>yours</em> in a way that disposable footwear can never be.</p>": "<p>But it's not just about money. Quality leather boots break in to the exact shape of your feet. After the first few weeks (yes, the break-in is real), they become the most comfortable shoes you own. They develop a patina that tells your story. They're <em>yours</em> in a way that disposable footwear can never be. If that logic appeals to you, it also shows up in <a href='/articles/best-bifl-wallets-for-men-leather-wallets-that-age-beautifully'>leather wallets that age beautifully</a> and <a href='/articles/best-red-wing-boots-a-complete-buyer-s-guide'>the broader Red Wing buyer's guide</a>.</p>",
    "<p>Taking care of quality leather boots is simple but important. Clean them with a <a href=\"https://www.amazon.com/s?k=horsehair+brush&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">horsehair brush</a> after wearing. Condition the leather every 2-3 months with a quality conditioner like <a href=\"https://www.amazon.com/dp/B001CS2Q4I?tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">Bick 4</a> or <a href=\"https://www.amazon.com/s?k=Red+Wing+boot+cream&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">Red Wing's own boot cream</a>. If they get soaked, stuff them with newspaper and let them dry naturally — never use heat.</p>": "<p>Taking care of quality leather boots is simple but important. Clean them with a <a href=\"https://www.amazon.com/s?k=horsehair+brush&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">horsehair brush</a> after wearing. Condition the leather every 2-3 months with a quality conditioner like <a href=\"https://www.amazon.com/dp/B001CS2Q4I?tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">Bick 4</a> or <a href=\"https://www.amazon.com/s?k=Red+Wing+boot+cream&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">Red Wing's own boot cream</a>. If they get soaked, stuff them with newspaper and let them dry naturally — never use heat. The same care discipline pays off with <a href='/articles/best-buy-it-for-life-rain-jackets'>rain jackets</a> and <a href='/articles/best-darn-tough-socks-the-only-socks-with-a-lifetime-guarantee'>Darn Tough socks</a>.</p>",
    "<p>Whether it's finding your car in a dark parking lot, checking under furniture, navigating a power outage, or signaling for help, a good flashlight earns its pocket space every single day.</p>": "<p>Whether it's finding your car in a dark parking lot, checking under furniture, navigating a power outage, or signaling for help, a good flashlight earns its pocket space every single day. It also pairs naturally with other practical carry gear like a <a href='/articles/best-bifl-wallets-for-men-leather-wallets-that-age-beautifully'>wallet that ages beautifully</a> or one of the <a href='/articles/best-buy-it-for-life-backpacks'>best buy-it-for-life backpacks</a>.</p>",
    "<p>The best EDC flashlight is the one you actually carry. That means size and weight matter as much as lumens. Look for a light that fits comfortably in your pocket with a good clip. Two brightness modes is the sweet spot — a low mode for close-up tasks and a high mode for distance.</p>": "<p>The best EDC flashlight is the one you actually carry. That means size and weight matter as much as lumens. Look for a light that fits comfortably in your pocket with a good clip. Two brightness modes is the sweet spot — a low mode for close-up tasks and a high mode for distance. That same boring practicality is why <a href='/articles/best-mechanical-watches-that-last-a-lifetime'>mechanical watches</a> and <a href='/articles/best-stainless-steel-water-bottles-that-last-forever'>stainless steel bottles</a> keep earning long-term loyalty.</p>",
    "<p>Most kitchen gear is disposable. Non-stick pans degrade in two years. Sheet pans warp. Cheap stockpots corrode. A quality Dutch oven operates on a completely different timeline. The right enameled cast iron or bare cast iron pot can serve your family for 50 years or more — and the only maintenance required is occasional re-seasoning for bare iron, or a little Bar Keepers Friend for enamel.</p>": "<p>Most kitchen gear is disposable. Non-stick pans degrade in two years. Sheet pans warp. Cheap stockpots corrode. A quality Dutch oven operates on a completely different timeline. The right enameled cast iron or bare cast iron pot can serve your family for 50 years or more — and the only maintenance required is occasional re-seasoning for bare iron, or a little Bar Keepers Friend for enamel. It is the same kitchen philosophy behind a <a href='/articles/best-cast-iron-skillets-that-last-forever'>cast iron skillet</a>, a <a href='/articles/best-kitchen-knives-that-last-a-lifetime'>lasting chef's knife</a>, and <a href='/articles/best-lodge-cast-iron-pieces-the-complete-collection-guide'>the broader Lodge cast iron lineup</a>.</p>",
    "<p>Hand wash only — dishwashers can dull and degrade enamel over time. Use wooden, silicone, or nylon utensils; metal can scratch enamel interiors. Let it cool before washing to avoid thermal shock. For stubborn stains on light interiors, <a href=\"https://www.amazon.com/dp/B000V72992?tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">Bar Keepers Friend</a> works wonders. Store with the lid slightly ajar to allow airflow. Never preheat an empty Dutch oven — always add oil or liquid before applying heat.</p>": "<p>Hand wash only — dishwashers can dull and degrade enamel over time. Use wooden, silicone, or nylon utensils; metal can scratch enamel interiors. Let it cool before washing to avoid thermal shock. For stubborn stains on light interiors, <a href=\"https://www.amazon.com/dp/B000V72992?tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">Bar Keepers Friend</a> works wonders. Store with the lid slightly ajar to allow airflow. Never preheat an empty Dutch oven — always add oil or liquid before applying heat. If you care enough to maintain a Dutch oven properly, you will probably also appreciate <a href='/articles/best-cast-iron-skillets-that-last-forever'>cast iron skillet care</a> and <a href='/articles/best-peelers-that-last-for-years'>durable prep tools</a>.</p>",
    "<p>Unlike digital devices, a mechanical watch has no obsolescence built in. The movement inside a Rolex Submariner made in 1970 is still being serviced by watchmakers today. Parts are machined, not manufactured with expiration dates. When something breaks, it can be fixed — often by skilled watchmakers anywhere in the world.</p>": "<p>Unlike digital devices, a mechanical watch has no obsolescence built in. The movement inside a Rolex Submariner made in 1970 is still being serviced by watchmakers today. Parts are machined, not manufactured with expiration dates. When something breaks, it can be fixed — often by skilled watchmakers anywhere in the world. That serviceability mindset also explains the appeal of <a href='/articles/best-red-wing-boots-a-complete-buyer-s-guide'>Red Wing boots</a> and <a href='/articles/best-woodworking-hand-tools-that-last-forever'>woodworking hand tools built for decades</a>.</p>",
    "<p><strong>Service intervals:</strong> Most mechanical watches need servicing every 5–10 years depending on movement type. Budget $200–$600 for most service-grade watches; more for Rolex/Omega. The Co-Axial escapement in Omega movements requires less lubrication and can go 8–10 years between services.</p>": "<p><strong>Service intervals:</strong> Most mechanical watches need servicing every 5–10 years depending on movement type. Budget $200–$600 for most service-grade watches; more for Rolex/Omega. The Co-Axial escapement in Omega movements requires less lubrication and can go 8–10 years between services. If you value gear that can be maintained instead of thrown away, also look at <a href='/articles/best-edc-flashlights-that-last-forever'>EDC flashlights</a> and <a href='/articles/best-bifl-wallets-for-men-leather-wallets-that-age-beautifully'>quality wallets</a>.</p>",
    "<p>Power tools get the glory, but hand tools are the soul of woodworking. They're quieter, more precise for fine work, and — critically — they're entirely serviceable. There are no motors to burn out, no batteries to degrade, no electronics to fail. A chisel is steel and a handle. A hand plane is cast iron, steel, and wood. These materials last essentially forever with proper care.</p>": "<p>Power tools get the glory, but hand tools are the soul of woodworking. They're quieter, more precise for fine work, and critically, they're entirely serviceable. There are no motors to burn out, no batteries to degrade, no electronics to fail. A chisel is steel and a handle. A hand plane is cast iron, steel, and wood. These materials last essentially forever with proper care. If you respect that kind of mechanical honesty, you will probably also appreciate <a href='/articles/best-estwing-hammers-that-last-a-lifetime'>Estwing hammers</a> and <a href='/articles/best-mechanical-watches-that-last-a-lifetime'>mechanical watches</a>.</p>",
    "<p><strong>Sharpening is everything.</strong> A sharp tool is safe and pleasurable to use. Learn to sharpen using <a href=\"https://www.amazon.com/s?k=waterstones+1000+4000+8000+grit&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">waterstones (1000 → 4000 → 8000 grit)</a> or <a href=\"https://www.amazon.com/s?k=diamond+plates&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">diamond plates</a>, and finish on a loaded <a href=\"https://www.amazon.com/s?k=leather+strop&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">leather strop</a>. A <a href=\"https://www.amazon.com/s?k=honing+guide&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">honing guide</a> ensures consistent bevel angles for beginners.</p>": "<p><strong>Sharpening is everything.</strong> A sharp tool is safe and pleasurable to use. Learn to sharpen using <a href=\"https://www.amazon.com/s?k=waterstones+1000+4000+8000+grit&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">waterstones (1000 → 4000 → 8000 grit)</a> or <a href=\"https://www.amazon.com/s?k=diamond+plates&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">diamond plates</a>, and finish on a loaded <a href=\"https://www.amazon.com/s?k=leather+strop&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">leather strop</a>. A <a href=\"https://www.amazon.com/s?k=honing+guide&tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">honing guide</a> ensures consistent bevel angles for beginners. Kitchen people will recognize the same discipline from maintaining <a href='/articles/best-kitchen-knives-that-last-a-lifetime'>chef's knives</a> and <a href='/articles/best-buy-it-for-life-chef-s-knives-professional-picks'>professional knife picks</a>.</p>",
    "<p>Cast iron cookware is a staple in many kitchens due to its durability and versatility. Among the best brands out there, Lodge stands out with their wide range of high-quality cast iron pieces. In this guide, we'll explore some of the most popular and useful items in the Lodge lineup that are worth considering for your collection.</p>": "<p>Cast iron cookware is a staple in many kitchens due to its durability and versatility. Among the best brands out there, Lodge stands out with their wide range of high-quality cast iron pieces. In this guide, we'll explore some of the most popular and useful items in the Lodge lineup that are worth considering for your collection. If you want the short version first, start with our guides to <a href='/articles/best-cast-iron-skillets-that-last-forever'>cast iron skillets that last forever</a> and <a href='/articles/best-dutch-ovens-that-last-forever'>Dutch ovens that last forever</a>.</p>",
    "<p>Or you can buy one wallet. A <strong>really</strong> good one. Full-grain leather, hand-stitched or saddle-stitched, from a maker who actually gives a damn. A wallet like that doesn't just survive — it develops a patina that tells your story. Five years in, it looks better than the day you bought it. Twenty years in, it's an heirloom.</p>": "<p>Or you can buy one wallet. A <strong>really</strong> good one. Full-grain leather, hand-stitched or saddle-stitched, from a maker who actually gives a damn. A wallet like that doesn't just survive, it develops a patina that tells your story. Five years in, it looks better than the day you bought it. Twenty years in, it's an heirloom. That same wear-instead-of-wear-out appeal is why people obsess over <a href='/articles/best-leather-boots-that-last-20-years'>leather boots that last 20 years</a> and <a href='/articles/best-buy-it-for-life-backpacks'>backpacks built for decades</a>.</p>",
    "<li><strong>Rotate your cards.</strong> Don't stuff 15 cards in a 6-slot wallet. Over-stuffing stretches the leather permanently.</li>": "<li><strong>Rotate your cards.</strong> Don't stuff 15 cards in a 6-slot wallet. Over-stuffing stretches the leather permanently, just like overloading <a href='/articles/best-buy-it-for-life-backpacks'>a backpack</a> or neglecting care on <a href='/articles/best-leather-boots-that-last-20-years'>quality boots</a> shortens a good product's life.</li>",
    "<p>A truly BIFL rain jacket either uses materials that don't degrade (waxed cotton), membranes that can be refreshed indefinitely (quality Gore-Tex), or comes with a warranty so ironclad that the manufacturer will replace it when it fails. We tested seven jackets over six months in Seattle rain — the real proving ground — to find the ones that earn the \"buy it for life\" label.</p>": "<p>A truly BIFL rain jacket either uses materials that don't degrade (waxed cotton), membranes that can be refreshed indefinitely (quality Gore-Tex), or comes with a warranty so ironclad that the manufacturer will replace it when it fails. We tested seven jackets over six months in Seattle rain, the real proving ground, to find the ones that earn the \"buy it for life\" label. They pair especially well with <a href='/articles/best-leather-boots-that-last-20-years'>boots built for decades</a> and <a href='/articles/best-buy-it-for-life-backpacks'>packs that can take abuse</a>.</p>",
    "<li><strong>Repair small damage immediately.</strong> A tiny tear or failed seam tape is an easy fix with <a href=\"https://www.amazon.com/dp/B077TMSQHV?tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">Gear Aid Tenacious Tape</a>. Left untreated, it spreads.</li>": "<li><strong>Repair small damage immediately.</strong> A tiny tear or failed seam tape is an easy fix with <a href=\"https://www.amazon.com/dp/B077TMSQHV?tag=everlastin08f-20\" target=\"_blank\" rel=\"nofollow noopener\">Gear Aid Tenacious Tape</a>. Left untreated, it spreads. That same repair-it-early instinct is what keeps <a href='/articles/best-red-wing-boots-a-complete-buyer-s-guide'>good boots</a> and <a href='/articles/best-bifl-wallets-for-men-leather-wallets-that-age-beautifully'>leather wallets</a> alive for years.</li>",
    "<p>Evaluating stainless steel water bottles that promise longevity requires looking beyond just the initial purchase price and quality of materials. It's about assessing durability, repairability, and overall service life. In this guide, we’ll dive into five top picks that stand out for their robust construction and lasting appeal.</p>": "<p>Evaluating stainless steel water bottles that promise longevity requires looking beyond just the initial purchase price and quality of materials. It's about assessing durability, repairability, and overall service life. In this guide, we’ll dive into five top picks that stand out for their robust construction and lasting appeal. If you like this kind of practical daily-use gear, also see our picks for <a href='/articles/best-edc-flashlights-that-last-forever'>EDC flashlights</a> and <a href='/articles/best-buy-it-for-life-backpacks'>buy-it-for-life backpacks</a>.</p>",
}

for old, new in replacements.items():
    if old not in text:
        print('MISSING REPLACEMENT TARGET:', old[:120])
    else:
        text = text.replace(old, new, 1)

faq_map = {
    'best-buy-it-for-life-japan-picks': [
        ("What should I buy in Japan if I want something that actually lasts?", "Start with practical gear like Zojirushi thermoses, Kai shears, Feather nail clippers, Pilot pens, and Seiko watches. They solve real daily problems and have reputations built on long-term use, not tourist hype."),
        ("Are Japanese knives and stationery automatically buy-it-for-life?", "No. Japan makes some superb tools, but it also sells plenty of well-packaged junk. Judge the steel, repairability, and real-world track record, not the country-of-origin label."),
        ("Is a Zojirushi mug the safest durable purchase from Japan?", "Yes, for most people it is the easiest recommendation. It is compact, genuinely useful, and absurdly good at the one job it is supposed to do."),
        ("What should I skip when shopping for durable goods in Japan?", "Skip souvenir-grade knives, fragile ceramics, and premium-looking lifestyle clutter with no long-term reputation. Boring tools beat novelty every time."),
    ],
    'best-e-readers-that-actually-last': [
        ("Which e-reader lasts the longest for most people?", "Usually the Kindle Paperwhite or a simple Kobo model. They keep the hardware and software restrained, which is exactly why they tend to age better than more ambitious devices."),
        ("Are e-readers actually buy-it-for-life products?", "Not literally. They are still electronics, but compared with phones and tablets they can deliver an unusually long, low-drama service life if you protect the screen and do not abuse the battery."),
        ("Is a Kindle better than a Kobo for long-term durability?", "Kindle has the safer ecosystem and support story, while Kobo offers more openness. Both can last well if you want a simple reader rather than a tiny do-everything tablet."),
        ("What helps an e-reader last longer?", "Use a case, avoid heat, charge it sanely, and do not clutter it with hacks you do not need. Most e-reader deaths are boring and preventable."),
    ],
    'best-peelers-that-last-for-years': [
        ("What type of peeler lasts the longest in a home kitchen?", "A well-made stainless steel or ceramic Y-peeler is usually the sweet spot. The best ones stay sharp, feel stable in hand, and do not loosen up after a few months."),
        ("Are ceramic peelers better than stainless steel peelers?", "They are better for rust resistance and edge retention, but worse at tolerating abuse. Ceramic is great if you treat it like a cutting tool instead of a pry bar."),
        ("Why do cooks keep recommending the Kuhn Rikon peeler?", "Because it is cheap, sharp, light, and weirdly effective. It proves a kitchen tool does not have to be expensive to be right."),
        ("How long should a good vegetable peeler last?", "Several years is a fair expectation with normal home use. If it dulls quickly or starts wobbling early, it was cheap junk from the start."),
    ],
}

def build_faq_html(items):
    parts = ['<h2>FAQ</h2>', '<div class="faq-section">']
    for q, a in items:
        parts.append(f'<div class="faq-item"><h3 class="faq-question">{q}</h3><p>{a}</p></div>')
    parts.append('</div>')
    return '\n'.join(parts)

for slug, items in faq_map.items():
    pattern = rf'(slug:\s*"{re.escape(slug)}".*?<h2>FAQ</h2>\n<div class="faq-section">.*?</div>\n\s*`,)'
    m = re.search(pattern, text, re.S)
    if not m:
        print('FAQ block not found for', slug)
        continue
    block = m.group(1)
    new_block = re.sub(r'<h2>FAQ</h2>\n<div class="faq-section">.*?</div>\n\s*`,', build_faq_html(items) + '\n    `,', block, flags=re.S)
    text = text.replace(block, new_block, 1)

path.write_text(text)
print('done')
